# Generated by Django 3.0.4 on 2020-07-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('imageprofile', models.ImageField(default='', upload_to='shop/images')),
                ('linedinid', models.CharField(max_length=100)),
                ('Thought', models.CharField(max_length=100)),
            ],
        ),
    ]
