# Generated by Django 2.2 on 2020-11-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_auto_20200727_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsorid', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default='', upload_to='sponsor/images')),
                ('name', models.TextField(max_length=200)),
            ],
        ),
    ]
